---
# Application info
info:
  app:
    name: Payconiq Stock MVP.
    description: An MVP as per Payconiq requirments for Senior BackEnd Engineer role.
    javaVersion: ${java.version}
    operatingSystem: ${os.name} ${os.version} (${os.arch})

# General Spring configuration
spring:
  main:
    banner-mode: "off"
  jackson:
    default-property-inclusion: NON_EMPTY
    deserialization:
      fail-on-unknown-properties: false
    serialization:
      write-dates-as-timestamps: false
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password:
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

# The base path for the Spring Actuator APIs
management:
  endpoint.health.show-details: "always"
  endpoints.enabled-by-default: true
  endpoints.web.exposure.include: "*"
  endpoints.jmx.exposure.include: "*"

# Configuration for Logback.
logging:
  config: classpath:logback-spring.xml

logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE

